language: php

php:
    - 5.3
    - 5.4

before_script:
    - composer install --dev
    - npm install --quiet uglify-js@1 && mkdir -p vendor/uglifyjs && mv node_modules vendor/uglifyjs
    - npm install --quiet coffee-script handlebars less stylus uglifycss uglify-js
    - gem install compass

script: phpunit -vc .travis.phpunit.xml
